delveryclub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('startpage.urls', namespace='startpage')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

startpage/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Startpage, BasketAdd, BasketView, BasketRemoveItemView, BasketRemoveView, BisnessMenuView, BasketAddItem,\
OrderView

app_name = 'startpage'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Startpage.as_view(), name='startpage'),
    path('add/<int:product_id>/', BasketAdd.as_view(), name='basket_add'),
    path('rem_item/<int:product_id>/', BasketRemoveItemView.as_view(), name='basket_rem_item'),
    path('add_item/<int:product_id>/', BasketAddItem.as_view(), name='basket_add_item'),
    path('rem/', BasketRemoveView.as_view(), name='basket_rem'),
    path('basket/', BasketView.as_view(), name='basket'),
    path('bmenu/', BisnessMenuView.as_view(), name='bmenu'),
    path('orders/', OrderView.as_view(), name='orders'),
    path('orders/<int:order_id>/', OrderView.as_view(), name='order'),
]

startpage/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import AnonymousUser


class User(AbstractUser):
    username = models.CharField(max_length=150, unique=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    address = models.ForeignKey('Address', on_delete=models.CASCADE, blank=True, null=True)
    device = models.CharField(max_length=256)

    def __str__(self):
        if self.username:
            username = self.username
        else:
            username = self.device
        return str(username)


class Address(models.Model):
    street = models.CharField(max_length=150)
    city = models.CharField(max_length=100)
    hause = models.CharField(max_length=100)
    apartment = models.CharField(max_length=100)
    orders = models.ForeignKey('Order', on_delete=models.CASCADE, blank=True, null=True)


class BasketQuerySet(models.QuerySet):

    def total_sum(self):
        return sum(basket.total() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    order = models.ForeignKey('Order', on_delete=models.CASCADE, null=True, blank=True)
    objects = BasketQuerySet.as_manager()

    def total(self):
        return self.quantity * self.product.price


class Product(models.Model):

    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    is_active = models.BooleanField()
    category = models.ForeignKey('Category', on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_at',)  # Делаем сортировку по дате публикации
        indexes = (
            models.Index(fields=['-created_at']),  # Добавляем индексы для ускорения работы с базой данных
        )

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products_images')


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    delivery_option = models.ForeignKey('DeliveryOption', on_delete=models.CASCADE, blank=True, null=True)
    total_sum = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return str(self.id)


class DeliveryOption(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class RecurringDeliverySchedule(models.Model):  
    delivery_option = models.ForeignKey(DeliveryOption, on_delete=models.CASCADE)    
    start_date = models.DateField()
    end_date = models.DateField()


class DeliveryAtAddress(models.Model):
   delivery_option = models.ForeignKey(DeliveryOption, on_delete=models.CASCADE)
   address = models.ForeignKey(Address, on_delete=models.CASCADE)
   
   
   git filter-branch --force --index-filter "git rm --cached --ignore-unmatch static/vezb3ky9.exe --prune-empty --tag-name-filter cat -- --all

startpage/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from startpage.models import Order, DeliveryOption, Address


class AdressForms(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['street', 'city', 'hause', 'apartment']

startpage/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, HttpResponse, get_object_or_404, reverse
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from .geocheack import start
from .forms import *
from .models import *
import uuid
from icecream import ic


class Startpage(View):

    def get(self, request: HttpResponse):
        print('trolololo')
        if request.user.is_authenticated:
            user = request.user
        else:
            device = request.COOKIES.get('device')
            if not device:
                device = request.session.session_key or str(uuid.uuid4())
                print(device)

            try:
                user = User.objects.get(device=device)
            except User.DoesNotExist:
                user = User.objects.create(device=device)

        basket_quantity = Basket.objects.filter(user=user).total_quantity()
        product = Product.objects.all()[:10]
        context = {
            'title': 'Главная',
            'product': product,
            'basket_quantity': basket_quantity,
        }

        # Если заголовок X-Requested-With указывает на AJAX-запрос, возвращаем JSON
        if request.headers.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
            response_data = {
                'basket_quantity': basket_quantity,
                # Другие данные, если необходимо
            }
            return JsonResponse(response_data)

            # В противном случае возвращать HTML-страницу
        return render(request, 'startpage/page1.html', context=context)

class BasketAdd(View):

    @csrf_exempt
    def post(self, request, product_id):
        product = Product.objects.get(id=product_id)
        if request.user.is_authenticated:
            user = request.user
        else:
            device = request.COOKIES.get('device')
            user, created = User.objects.get_or_create(device=device)
        baskets = Basket.objects.filter(user=user, product=product)
        if not baskets.exists():
            Basket.objects.create(user=user, product=product, quantity=1)
        else:
            basket = baskets.first()
            basket.quantity += 1
            basket.save()

        bask_quantity = Basket.objects.filter(user=user).total_quantity()

        return JsonResponse({'bask_quantity': bask_quantity})


class BasketView(View):

    def get(self, request):
        if request.user.is_authenticated:
            user = request.user
        else:
            device = request.COOKIES.get('device')
            user, created = User.objects.get_or_create(device=device)
        baskets = Basket.objects.filter(user=user)
        context = {
            'title': 'Корзина',
            'baskets': baskets,
        }
        return render(request, 'startpage/basket.html', context=context)


class BasketRemoveItemView(View):

    def get(self, request, product_id):

        product = get_object_or_404(Product, id=product_id)

        if request.user.is_authenticated:
            user = request.user
        else:
            device = request.COOKIES.get('device')
            user, _ = User.objects.get_or_create(device=device)

        basket = Basket.objects.filter(user=user, product=product).first()

        if basket.quantity >= 1:
            basket.quantity -= 1
            if basket.quantity == 0:
                basket.delete()
            else:
                basket.save()

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class BasketAddItem(View):

    def get(self, request, product_id):
        product = Product.objects.get(id=product_id)
        if request.user.is_authenticated:
            user = request.user
        else:
            device = request.COOKIES.get('device')
            user, created = User.objects.get_or_create(device=device)
        baskets = Basket.objects.filter(user=user, product=product)
        if not baskets.exists():
            Basket.objects.create(user=user, product=product, quantity=1)
        else:
            basket = baskets.first()
            basket.quantity += 1
            basket.save()

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class BasketRemoveView(View):

    def get(self, request):
        if request.user.is_authenticated:
            user = request.user
        else:
            device = request.COOKIES.get('device')
            user, _ = User.objects.get_or_create(device=device)

        baskets = Basket.objects.filter(user=user)
        for basket in baskets:
            basket.delete()
        return HttpResponseRedirect(reverse('startpage:startpage'))


class BisnessMenuView(View):
    def get(self, request):
        if request.user.is_authenticated:
            user = request.user
        else:
            device = request.COOKIES.get('device')
            user, _ = User.objects.get_or_create(device=device)
        product = Product.objects.all()
        baskets = Basket.objects.filter(user=user)
        context = {
            'title': 'Бизнес меню',
            'product': product,
            'baskets': baskets,
        }
        return render(request, 'startpage/bisneslaunch.html', context=context)


class OrderView(View):
    def get(self, request):
        if request.user.is_authenticated:
            user = request.user
        else:
            device = request.COOKIES.get('device')
            if not device:
                device = request.session.session_key or str(uuid.uuid4())
                print(device)

            try:
                user = User.objects.get(device=device)
            except User.DoesNotExist:
                user = User.objects.create(device=device)
        baskets = Basket.objects.filter(user=user)
        order = Order.objects.filter(user=user).first()
        total_sum = baskets.total_sum()

        if not order:
            order = Order.objects.create(user=user, quantity=1, total_sum=total_sum)
            for basket in baskets:
                basket.order = order
                basket.save()
        else:
            order.total_sum = total_sum
            order.save()
        context = {
            'title': 'Заказ',
            'order': order,
            'form': AdressForms(),
            'delivery': DeliveryOption.objects.filter(order=order).first(),
        }
        print(context)
        return render(request, 'startpage/order.html', context=context)

    def post(self, request, order_id):
        form = AdressForms(request.POST)
        if form.is_valid():
            adress = f"{form.cleaned_data['city']} {form.cleaned_data['street']} {form.cleaned_data['hause']}"
            dist_price = start(adress)

            order = get_object_or_404(Order, id=order_id)
            dely = DeliveryOption.objects.create(name=adress, price=dist_price)
            adress = Address.objects.create(orders=order, **form.cleaned_data)
            order.adress = adress
            order.delivery_option = dely
            order.save()
            return HttpResponseRedirect(reverse('startpage:orders'))

startpage/templates/startpage/basket.html
{% extends 'startpage\base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'nicepage.css' %}" media="screen">
{% endblock %}
{% block content %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <section class="u-align-center u-clearfix u-section-2" id="sec-171d">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="custom-expanded u-table u-table-responsive u-table-1">
            <div class="container">
              <table class="u-align-center u-table-entity u-table-entity-1" style="margin-left: auto; margin-right: auto;">
                <colgroup>
                  <col width="25%">
                  <col width="25.4%">
                  <col width="24.6%">
                  <col width="25%">
                </colgroup>
                <thead class="u-grey-50 u-table-header u-table-header-1">
                  <tr style="height: 44px;">
                    <th class="u-border-1 u-border-grey-50 u-table-cell">product</th>
                    <th class="u-border-1 u-border-grey-50 u-table-cell">quantity</th>
                    <th class="u-border-1 u-border-grey-50 u-table-cell">price</th>
                    <th class="u-border-1 u-border-grey-50 u-table-cell">action</th>
                  </tr>
                </thead>
                <tbody class="u-table-body">
                {% for basket in baskets %}
                    <tr style="height: 44px;">
                    <td class="u-border-1 u-border-grey-40 u-border-no-left u-border-no-right u-table-cell">{{ basket.product.name }}</td>
                    <td class="u-border-1 u-border-grey-40 u-border-no-left u-border-no-right u-table-cell">
                        <a href="{% url 'startpage:basket_rem_item' basket.product.id %}" class="button-minus">-</a>

                            <span>{{ basket.quantity }}</span>

                        <a href="{% url 'startpage:basket_add_item' basket.product.id %}" class="button-plus">+</a>
                    </td>
                    <td class="u-border-1 u-border-grey-40 u-border-no-left u-border-no-right u-table-cell">{{ basket.total }}</td>
                    <td class="u-border-1 u-border-grey-40 u-border-no-left u-border-no-right u-table-cell">Description</td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
                <div class="u-container-style u-layout-cell u-size-40 u-layout-cell-2">
                  <div class="u-container-layout u-container-layout-2">
                      <h6 class="u-text u-text-default u-text-1">Общая сумма: {{ baskets.total_sum }}</h6>
                    <a href="https://nicepage.app" class="u-active-none u-border-5 u-border-active-palette-2-dark-1 u-border-hover-black u-border-no-left u-border-no-right u-border-no-top
                    u-border-palette-1-base u-btn u-button-style u-hover-none u-none u-text-body-color u-btn-1">Ссылка</a>
                    <a href="{% url 'startpage:basket_rem' %}" class="u-active-none u-border-5 u-border-active-palette-2-dark-1 u-border-hover-black u-border-no-left u-border-no-right u-border-no-top
                    u-border-palette-1-base u-btn u-button-style u-hover-none u-none u-text-body-color u-btn-1">Очистить корзину</a>
                  </div>
                </div>
                <div class="u-container-style u-layout-cell u-size-40 u-layout-cell-2">
                    <div class="u-container-layout u-container-layout-2">

                    </div>
                </div>
            </div>
        </div>
      </div>
    </section>
{#        <section class="u-clearfix u-section-3" id="sec-9b01">#}
{#          <div class="data-layout-selected u-clearfix u-expanded-width u-layout-wrap u-layout-wrap-1">#}
{#            <div class="u-layout">#}
{#              <div class="u-layout-row">#}
{#                <div class="u-container-style u-layout-cell u-size-5 u-layout-cell-1">#}
{#                  <div class="u-container-layout u-container-layout-1"></div>#}
{#                </div>#}
{#                <div class="u-container-style u-layout-cell u-size-49 u-layout-cell-2">#}
{#                  <div class="u-container-layout u-container-layout-2"></div>#}
{#                </div>#}
{#                <div class="u-container-style u-layout-cell u-size-6 u-layout-cell-3">#}
{#                  <div class="u-container-layout u-container-layout-3"></div>#}
{#                </div>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
{#        </section>#}
{#        </div>#}
{#    </footer>#}

{% endblock %}

startpage/templates/startpage/bisneslaunch.html
{% extends 'startpage/base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}
{% block css %}
{#    <link rel="stylesheet" href="{% static 'nicepage2.css' %}" media="screen">#}
    <link rel="stylesheet" href="{% static 'nicepage.css' %}" media="screen">
    <style>
    .u-dropdown button {
      padding: 10px 20px;
    }

    .u-dropdown-content {
      display: none;
      position: absolute;
      background-color: #fff;
      min-width: 160px;
      box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
      z-index: 1;
    }

    .u-dropdown-content a {
      display: block;
      padding: 12px 16px;
      text-decoration: none;
      color: #333;
    }

    .u-dropdown-content a:hover {
      background-color: #f2f2f2;
    }

    .u-dropdown:hover .u-dropdown-content {
      display: block;
    }

    .container {
      display: flex;
      justify-content: flex-start;
    }
    .scrollable-modal-body {
        max-height: calc(100vh - 210px);
        overflow-y: auto;
    }
    .my-table {
    margin-left: auto;
    margin-right: auto;
    }

    .quantity-cell {
        display: flex;
        align-items: center;
        justify-content: space-between;
    }

    .button-minus,
    .button-plus {
        display: inline-block;
        padding: 5px;
        border: 1px solid #ddd;
        cursor: pointer;
    }

    .button-minus:hover,
    .button-plus:hover {
        background-color: #f5f5f5;
    }
    .my-table {
    margin: auto;
    }

    .quantity-cell {
        display: flex;
        align-items: center;
        justify-content: space-between;
    }

    .btn-danger,
    .btn-success {
        margin-top: 10px;
    }


    </style>
{% endblock %}
{% block content %}
    <br>
    <br>
    <br>
    <div class="container">
      <div class="row justify-content-center mt-5 flex-row">
        <div class="col">
          <img src="{% static '1647726000_2-amiel-club-p-kartinki-supa-2.jpg' %}" class="img-fluid" data-toggle="modal" data-target="#soupModal">
        </div>
        <div class="col">
          <img src="{% static '10-shikarnyh-goryachih-blyud-na-noviy-god.jpg' %}" class="img-fluid" data-toggle="modal" data-target="#mainDishModal">
        </div>
        <div class="col">
          <img src="{% static 'salat_sushi-555028.jpg' %}" class="img-fluid" data-toggle="modal" data-target="#saladModal">
        </div>
      </div>
    </div>

    <!-- Soup Modal -->
    <div class="modal fade" id="soupModal" tabindex="-1" role="dialog" aria-labelledby="soupModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="soupModalLabel">Супы</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body scrollable-modal-body">
              {% for item in product %}
                {% if item.category.name == 'супы' %}
                   <div class="card">
                        <div class="card-body">
                            <img src="{{ item.productimage_set.first.image.url }}" alt="{{ item.name }} Image" class="card-img-top">
                            <h5 class="card-title">{{ item.name }}</h5>
                            <p class="card-text">Price: {{ item.price }}</p>
                            <a href="{% url 'startpage:basket_add_item' item.id %}" class="btn btn-primary">Добавить в корзину</a>
                        </div>
                   </div>
                {% endif %}
              {% endfor %}
          </div>
        </div>
      </div>
    </div>

    <!-- Main Dish Modal -->
    <div class="modal fade" id="mainDishModal" tabindex="-1" role="dialog" aria-labelledby="mainDishModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="mainDishModalLabel">Вторые блюда</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body scrollable-modal-body">
              {% for item in product %}
                {% if item.category.name == 'горячее' %}
                    <div class="card">
                        <div class="card-body">
                            <img src="{{ item.productimage_set.first.image.url }}" alt="{{ item.name }} Image" class="card-img-top">
                            <h5 class="card-title">{{ item.name }}</h5>
                            <p class="card-text">Price: {{ item.price }}</p>
                            <a href="{% url 'startpage:basket_add_item' item.id %}" class="btn btn-primary">Добавить в корзину</a>
                        </div>
                    </div>
                {% endif %}
              {% endfor %}
          </div>
        </div>
      </div>
    </div>

    <!-- Salad Modal -->
    <div class="modal fade" id="saladModal" tabindex="-1" role="dialog" aria-labelledby="saladModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="saladModalLabel">Салаты</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body scrollable-modal-body">
              {% for item in product %}
                {% if item.category.name == 'салаты' %}
                    <div class="card">
                        <div class="card-body">
                            <img src="{{ item.productimage_set.first.image.url }}" alt="{{ item.name }} Image" class="card-img-top">
                            <h5 class="card-title">{{ item.name }}</h5>
                            <p class="card-text">Price: {{ item.price }}</p>
                            <a href="{% url 'startpage:basket_add_item' item.id %}" class="btn btn-primary">Добавить в корзину</a>
                        </div>
                    </div>
                {% endif %}
              {% endfor %}
          </div>
        </div>
      </div>
    </div>

<div class="container mt-5">
    <h2>Заказ: </h2>
    <div id="orderDetails">
        <div class="custom-expanded">
            <div class="container">
                <table class="table my-table">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">Product</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Price</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for basket in baskets %}
                            <tr>
                                <td>{{ basket.product.name }}</td>
                                <td class="quantity-cell">
                                    <a href="{% url 'startpage:basket_rem_item' basket.product.id %}" class="btn btn-sm btn-danger">-</a>
                                    <span>{{ basket.quantity }}</span>
                                    <a href="{% url 'startpage:basket_add_item' basket.product.id %}" class="btn btn-sm btn-success">+</a>
                                </td>
                                <td>{{ basket.total }}</td>
                            </tr>

                        {% endfor %}
                    </tbody>
                </table>
                <div class="u-container-style u-layout-cell u-size-40 u-layout-cell-2">
                    <div class="u-container-layout u-container-layout-2">
                        <h6 class="u-text u-text-default u-text-1">Общая сумма: {{ baskets.total_sum }}</h6>
                        <a href="{% url 'startpage:basket_rem' %}" class="btn btn-danger">Clear Basket</a>
                    </div>
                </div>
                <div class="u-container-style u-layout-cell u-size-40 u-layout-cell-2">
                    <div class="u-container-layout u-container-layout-2"></div>
                </div>
            </div>
        </div>
    </div>
    <a href="{% url 'startpage:orders' %}">
        <button type="button" class="btn btn-success mt-3">Оформить заказ</button>
    </a>
</div>
    <!-- jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
{% endblock %}

startpage/templates/startpage/order.html
{% extends 'startpage\base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'nicepage.css' %}" media="screen">
    <style>
    .btn {
        display: inline-block;
        padding: 10px 20px;
        font-size: 16px;
        text-decoration: none;
        background-color: #4CAF50;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }
    </style>
{% endblock %}
{% block content %}
    <br>
    <br>
    <section class="u-align-center u-clearfix u-section-2" id="sec-171d">
      <div class="u-clearfix u-sheet u-sheet-1">
          <p class="u-text u-text-default u-text-1">
            <p style="alignment-baseline: auto">
              Заказал: {{ order.user.username }}</p>
          Продукты:
              {% for bas in order.basket_set.all %}
                  <p style="alignment-baseline: auto">{{ bas.product.name }}</p>
              {% endfor %}
              </p>
               <p style="alignment-baseline: auto">
                  {{ order.basket_set.product.name }}</p>
               <p style="alignment-baseline: auto">
                  Общая стоимость: {{ order.total_sum }}</p>
                {% if delivery %}
                    <p style="alignment-baseline: auto">
                      Цена доставки: {{ delivery.price }}</p>
                {% endif %}



    </section>
    <section class="u-align-center u-clearfix u-section-2" id="sec-171d">
      <div class="u-clearfix u-sheet u-sheet-1">
          <form action="{% url 'startpage:order' order.id %}" method="post">
              {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary" value="применить">
          </form>
        <a href="/your-target-page" class="btn">Go to Another Page</a>
    </section>
{% endblock %}